import { poiret, raleway, roboto, josefina, inter } from '#@/styles/fonts';
import '#@/styles/globals.css';
import { Metadata } from 'next';
import './manifest';
import 'material-symbols';
import { ReactNode } from 'react';
import Script from 'next/script';
import { ModalProvider } from './context/modal-context';
import Header from '#@/components/layout/header';
import { SearchProvider } from './context/search-context';
import layout from '#@/styles/layout.module.css';


export const metadata: Metadata = {
  title      : 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(
  {
    children,
  }: {
  children: ReactNode
}
) {
  return (
    <html lang="es">
      <body className={ `${ poiret.variable } ${ raleway.variable } ${ inter.variable } ${ roboto.variable } ${ josefina.variable } [ color-scheme: light dark ]` }>
        <ModalProvider>
          <SearchProvider>
            <div className={ layout.container }>
              <Header >

              </Header>
              { children }
            </div>
          </SearchProvider>
        </ModalProvider>
      </body>
      <Script src={'service-worker.js'} />
    </html>
  );
}
